// বাংলাদেশের বহুল ব্যবহৃত ২০০+ ওষুধের পূর্ণাঙ্গ ডেটাবেজ (A থেকে Z পর্যন্ত)
const allMedicinesList = [
    // A দিয়ে শুরু
    "Napa Extra 500mg (Paracetamol)",
    "Napa 500mg Tablet",
    "Ace 500mg (Paracetamol)",
    "Ace Plus",
    "Alatrol 10mg (Cetirizine)",
    "Azithrocin 500mg (Azithromycin)",
    "Amoxicillin 500mg",
    "Aceclofenac 100mg",
    "Amodis 400mg (Metronidazole)",
    "Antacid Tablet",
    "Amlodipine 5mg",
    "Aspirin 75mg",
    "Atorvastatin 10mg",
    "Azithral 500mg",
    "Alizin Syrup",
    "Adovas Syrup",
    "Apar 500mg",
    "Albendazole 400mg",
    "Aciloc 150mg",
    "Aarogya Plus",

    // B দিয়ে শুরু
    "Bexicap 400mcg",
    "Baclofen 10mg",
    "Becosules Capsule",
    "Bicalutamide 50mg",
    "Bisoprolol 2.5mg",
    "Brohexine Syrup",
    "Boric Powder",
    "Buscopan 10mg (Hyoscine)",
    "Bcomplex Syrup",
    "Betnesol Tablet",
    "Bicalut 50mg",
    "Bidzen 50mg",
    "Bronyl Syrup",
    "Bilastine 20mg",
    "Bicalam Plus",

    // C দিয়ে শুরু
    "Ceevit 250mg (Vitamin C)",
    "Calbo-D (Calcium + Vit D3)",
    "Ciprocin 500mg (Ciprofloxacin)",
    "Ceix 200mg (Cefixime)",
    "Cetirizine 10mg",
    "Clonazepam 0.5mg",
    "Concor 5mg",
    "Cefuroxime 500mg",
    "Clindamycin 300mg",
    "Cetrizin Syrup",
    "Co-Amoxiclav 625mg",
    "Calci-D",
    "Candid V6 Vaginal Tablet",
    "Carbamazepine 200mg",
    "Cetirizine Syrup",

    // D দিয়ে শুরু
    "D-Cap 20000 IU (Vitamin D3)",
    "Diclac 50mg (Diclofenac)",
    "Domperidone 10mg",
    "Doxicycline 100mg",
    "Dosa 10mg",
    "Duvadilan 10mg",
    "Dextromethorphan Syrup",
    "Deriphyllin Tablet",
    "Desloratadine 5mg",
    "Diclophenac Sodium Gel",
    "Diazepam 5mg",
    "Digoxin 0.25mg",
    "Drotaverine 40mg",
    "Duphalac Syrup",
    "Dabigatran 110mg",

    // E দিয়ে শুরু
    "E-Cap 400mg (Vitamin E)",
    "Esonix 20mg (Esomeprazole)",
    "Etoricoxib 90mg",
    "Erythromycin 500mg",
    "Emlet 10mg",
    "Ecosprin 75mg",
    "Enam 5mg (Enalapril)",
    "Emeset 4mg (Ondansetron)",
    "Epilim 200mg",
    "Esoprazole 40mg",
    "Etoricox 120mg",
    "Ethambutol 800mg",
    "Evion 400mg",
    "Eze 10mg",

    // F দিয়ে শুরু
    "Fexo 120mg (Fexofenadine)",
    "Fexo 180mg",
    "Folic Acid 5mg",
    "Flucloxacillin 500mg",
    "Flagyl 400mg (Metronidazole)",
    "Flunarizine 10mg",
    "Furosemide 40mg",
    "Fluconazole 150mg",
    "Fexo Syrup",
    "Feosol Capsule",
    "Ferrous Sulfate",
    "Fentanyl Patch",
    "Foracort Inhaler",
    "Fucidin Cream",
    "Frusen 40mg",

    // G দিয়ে শুরু
    "Gaviscon Liquid & Tablet",
    "Glimepiride 2mg",
    "Gliclazide 80mg",
    "Gabapentin 300mg",
    "Gentamicin Eye Drop",
    "Glibenclamide 5mg",
    "Glycerin Suppository",
    "Gdriver Syrup",
    "Gemfibrozil 600mg",
    "Grep 10mg",
    "Glucophage 500mg (Metformin)",
    "Griseofulvin 500mg",
    "Guaifenesin Syrup",
    "Gestoden Tablet",

    // H দিয়ে শুরু
    "Histacin 4mg (Chlorpheniramine)",
    "Hydrocortisone Cream",
    "Hyoscine Butylbromide",
    "Hydralazine 25mg",
    "Hydrochlorothiazide 25mg",
    "Hifenac-P",
    "Human Insulin",
    "Hyperheal Ointment",
    "Helicobacter Test Kit",
    "Heparin Injection",
    "Haloperidol 5mg",
    "Hematinic Capsule",

    // I দিয়ে শুরু
    "Inposer 20mg (Omeprazole)",
    "Ibugesic Plus (Ibuprofen + Paracetamol)",
    "Indapamide 1.5mg",
    "Itraconazole 200mg",
    "Ibuprofen 400mg",
    "Insulin Glargine",
    "Ipratropium Inhaler",
    "Iron Syrup",
    "Isosorbide Dinitrate 5mg",
    "Iohexol Injection",
    "Ivermectin 6mg",
    "Imipramine 25mg",

    // J-K দিয়ে শুরু
    "Jardiance 10mg (Empagliflozin)",
    "Januvia 100mg (Sitagliptin)",
    "Jectocos Injection",
    "Ketoroloc 10mg",
    "Ketoconazole Cream",
    "Keto 200mg",
    "K-Gard Capsule",
    "Kalium Carbonicum",
    "Kcl Syrup",
    "Knee Gel",

    // L দিয়ে শুরু
    "Losec M 20mg (Omeprazole)",
    "Lisinopril 10mg",
    "Losartan Potassium 50mg",
    "Levo 500mg (Levofloxacin)",
    "Loratadine 10mg",
    "Lactulose Solution",
    "Linagliptin 5mg",
    "Luliconazole Cream",
    "Loperamide 2mg",
    "Levetiracetam 500mg",
    "Lidocaine Spray",
    "Liv-52 Syrup",
    "Lanolin Ointment",
    "Lexotan 3mg",

    // M দিয়ে শুরু
    "Maxpro 20mg (Esomeprazole)",
    "Maxpro 40mg",
    "Monas 10mg (Montelukast)",
    "Metformin 500mg",
    "Metronidazole 400mg",
    "Moxifloxacin 400mg",
    "Meclizine 25mg",
    "Methylprednisolone 4mg",
    "Multivitamin Capsule",
    "Mupirocin Ointment",
    "Mebendazole 100mg",
    "Meloxicam 15mg",
    "Minoxidil 5%",
    "Miconazole Gel",
    "Midazolam 7.5mg",

    // N দিয়ে শুরু
    "Napa Extend 665mg",
    "Napa Drop (Baby)",
    "Nexum 20mg (Esomeprazole)",
    "Neotot 500mg",
    "Nurobion Forte (Vitamin B Complex)",
    "Nifedipine 20mg",
    "Nitrofurantoin 100mg",
    "Nizatidine 150mg",
    "Nystatin Oral Drop",
    "Norfloxacin 400mg",
    "Nandrolone Injection",
    "Nicotine Gum",
    "Nebivolol 5mg",
    "Nimesulide 100mg",

    // O দিয়ে শুরু
    "Omidon 10mg (Domperidone)",
    "Ornidazole 500mg",
    "Omez 20mg",
    "Ondem 4mg",
    "Oflokacin 200mg",
    "Ointment Zinc Oxide",
    "Osteocare Liquid",
    "Oxytocin Injection",
    "Oracort Dental Paste",
    "Ofloxacin Eye Drop",
    "Oestrogen Tablet",

    // P দিয়ে শুরু
    "Progut 3mg (Probiotic)",
    "Pantix 75mg (Clopidogrel)",
    "Pantonic 40mg (Pantoprazole)",
    "Pancreatin Capsule",
    "Paracetamol 500mg",
    "Pyrazinamide 500mg",
    "Prednisolone 5mg",
    "Promethazine 25mg",
    "Pyritinol 100mg",
    "Povidone Iodine Ointment",
    "Pyrantel Pamoate",
    "Pregabalin 75mg",
    "Propranolol 40mg",

    // R দিয়ে শুরু
    "Rabecon 20mg (Rabeprazole)",
    "Ranitidine 150mg",
    "Rifampicin 450mg",
    "Rosuvastatin 10mg",
    "Roxid 150mg",
    "Rexpression Syrup",
    "Rinotin Drop",
    "Rhumagesic Oil",
    "Rablet 20mg",
    "Rifagut 550mg",
    "Rutin Tablet",

    // S দিয়ে শুরু
    "Seclo 20mg (Omeprazole)",
    "Sergel 20mg (Esomeprazole)",
    "Sergel 40mg",
    "Syrup Phensedyl",
    "Salbutamol 4mg",
    "Syp. Tixylix",
    "Syp. Ascoril",
    "Silver Sulfadiazine Cream",
    "Sildenafil 50mg",
    "Spironolactone 25mg",
    "Simvastatin 20mg",
    "Sucralfate Suspension",
    "Sulfasalazine 500mg",
    "Sumatriptan 50mg",

    // T দিয়ে শুরু
    "Tryptin 10mg (Amitriptyline)",
    "Telfast 120mg (Fexofenadine)",
    "Tramadol 50mg",
    "Thyroxine 100mcg",
    "Teneligliptin 20mg",
    "Timolol Eye Drop",
    "Tramadol Injection",
    "Terbinafine 250mg",
    "Tranexamic Acid 500mg",
    "Tetracycline 250mg",
    "Thiocolchicoside 4mg",
    "Tolperisone 150mg",

    // U-V-W-X-Y-Z দিয়ে শুরু
    "Uoric 40mg (Febuxostat)",
    "Udiliv 300mg",
    "Urimax 0.4mg",
    "Ultracet Tablet",
    "Vomistop 10mg",
    "Vitamin B-Complex",
    "Valproic Acid 500mg",
    "Vildagliptin 50mg",
    "Venlafaxine 75mg",
    "Verapamil 80mg",
    "Vigabatrin 500mg",
    "Warfarin 5mg",
    "Wysolone 5mg",
    "Xylometazoline Nasal Drop",
    "Xigduo XR Tablet",
    "Xanax 0.5mg",
    "Zincovit Tablet",
    "Zinc Sulfate 20mg",
    "Zithrox 500mg",
    "Zifi 200mg",
    "Zolpidem 10mg"
];